---

- name: Unarchive monogdb package.
  unarchive:
    src: "{{ mongodb_package }}"
    dest: /usr/local/src/
    remote_src: false
    creates: "/usr/local/src/mongo-{{ mongo_version }}"

- name: Compile mongodb.
  command: |
          /usr/bin/phpize
          ./configure
  args:
    chdir: "/usr/local/src/mongo-{{ mongo_version }}"
    creates: /usr/lib64/php/modules/mongo.so

- name: Install mongodb.
  command: |
          make -j{{ ansible_processor_cores|default(1) + 1 }}{{ ' 32bit' if redis_make_32bit|bool else '' }}
          make install
  args:
    chdir: "/usr/local/src/mongo-{{ mongo_version }}"
    creates: /usr/lib64/php/modules/mongo.so

- name: Copy php.ini
  copy:
    src: php.ini
    dest: /etc/php.ini
    remote_src: false
  notify: Restart php-fpm
