---
- name: Check if php-fpm is already installed.
  stat: path="/etc/systemd/system/php-fpm.service.d"
  register: php_fpm

- name: Install php If php_fpm is not install
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "remi,remi-php56"
  with_items:
    - "{{ php_packages }}"

- name: Confiugre php-fpm.
  template:
    remote_src: false
    src: www.conf.j2
    dest: /etc/php-fpm.d/
  notify: Start php-fpm.
