---

- name: Ensure that config directory is exists
  file: state=directory path="{{ software_dir }}"

- name: Upload remi-repo.
  copy:
    remote_src: false
    src: remi-release-7.rpm
    dest: "{{ software_dir }}"

- name: Install remi repo.
  yum:
    name: "{{ software_dir }}remi-release-7.rpm"
    state: present
