---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define php_packages.
  set_fact:
    php_packages: "{{ __php_packages }}"
  when: php_packages is not defined

- name: Define php_daemon.
  set_fact:
    php_daemon: "{{ __php_daemon }}"
  when: php_daemon is not defined
